### PR TITLE
Make DistributedResponseCacheStore internal

### PR DESCRIPTION
**Pull request by JunTaoLuo**
cc @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
I think @DamianEdwards asked to delete this entirely as we already know it won't work for future features.

**Comment by JunTaoLuo** [comment]
So there won't even be a fallback for not supporting more advanced features e.g. tag invalidation?

**Comment by JunTaoLuo** [comment]
Let's consider what other extensibility we want to remove for 1.1. It's possible that CacheEntries and PolicyProvider may also go away?

**Comment by JunTaoLuo** [comment]
:up::date:

**Pull request merged**
