### PR TITLE
We don't use the IMemoryCache from DI

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Instead we create a private instance: https://github.com/aspnet/ResponseCaching/blob/master/src/Microsoft.AspNetCore.ResponseCaching/ResponseCachingMiddleware.cs#L40-L43

### CODE REVIEW

**Comment by Tratcher** [comment]
Careful. Anybody that was resolving that memory cache can break if you remove it. 

Is that why you're doing it only in Master?

**Comment by Eilon** [comment]
Yeah this is a breaking change but I think a good one. I'd say it's fine for 3.0.

**Comment by JunTaoLuo** [comment]
Right, it's a breaking change but we shouldn't be adding services we don't use.

**Comment by Eilon** [comment]
I'm fine leaving 2.2 as-is, and fix only in 3.0. Mark the bug as breaking-change. (No need for an announcement unless someone complains.)

**Comment by Eilon** [comment]
Actually, *is* there an issue for this? If not, please log one.

**Comment by JunTaoLuo** [comment]
No there wasn't. Logged at: https://github.com/aspnet/Home/issues/3360.

**Pull request merged**
